import React from "react";

import "./style.css";

function Marquee() {
    return (
        <>
            <div class="slider">
                <ul>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%201"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%202"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%203"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%204"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%205"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%206"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%207"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%208"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%209"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%2010"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%2011"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%2012"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%2013"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%2014"
                            alt=""
                        />
                    </li>
                    <li>
                        <img
                            src="https://via.placeholder.com/200?text=Logo%2015"
                            alt=""
                        />
                    </li>
                </ul>
            </div>
        </>
    );
}

export default Marquee;
